language: ruby
rvm:
 - 2.2.1
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis_ci_test' -U postgres
services:
  - postgresql
addons:
  postgresql: "9.4"
# uncomment and edit the following line if your project needs to run something other than `rake`:
#script: bundle exec rspec spec